name: CI/CD to IIS

on:
  push:
    branches:
      - master # 更改為您的主要分支名稱

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build .NET Framework 4.8 solution
      run: msbuild YourProject.sln /p:Configuration=Release

    - name: Publish the project
      run: msbuild YourProject.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=YourPublishProfile.pubxml

    - name: Deploy to IIS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IIS_HOST }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        port: 22
        source: "path/to/your/published/files/*"
        target: "/path/on/iis"
