name: CI/CD to IIS

on:
  push:
    branches:
      - master # 更改為您的主要分支名稱

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSBuild and Visual Studio components
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
        choco install visualstudio-installer
        export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin"

    - name: Locate MSBuild
      id: msbuild
      run: |
        $msbuild = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "MSBuild path is: $msbuild"
        echo "##[set-output name=msbuild_path;$msbuild]"

    - name: Build .NET Framework 4.8 solution
      run: |
        ${{ steps.msbuild.outputs.msbuild_path }} YourProject.sln /p:Configuration=Release

    - name: Publish the project
      run: |
        ${{ steps.msbuild.outputs.msbuild_path }} YourProject.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=YourPublishProfile.pubxml

    - name: Deploy to IIS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IIS_HOST }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        port: 22
        source: "path/to/your/published/files/*"
        target: "/path/on/iis"
